1. Un cuaderno Jupyter es un servicio de ejecucion de codigo python online. Esta conformado por un conjunto de celdas en las cuales ponemos nuestro codigo y lo podemos ejecutar, o tambien podemos escribir texto (esas son las celdas de codigo y de texto).
2. 
Un entorno de ejecución en Jupyter se refiere a la instancia de un intérprete (como Python) que ejecuta el código contenido en las celdas de código del cuaderno. Este entorno incluye las variables, las funciones, y el estado general del cuaderno durante la sesión. La duración de una sesión de un entorno de ejecución depende del entorno en el que se esté utilizando Jupyter: Localmente: Si estás ejecutando Jupyter en tu computadora, la sesión dura mientras tengas la aplicación abierta y en ejecución. Si cierras el cuaderno o apagas tu computadora, la sesión termina. En la nube: Si estás usando un servicio en la nube (como Google Colab), la sesión tiene un tiempo de inactividad predeterminado (generalmente 90 minutos de inactividad o 12 horas de ejecución continuada) antes de desconectar el entorno. Esto puede variar dependiendo del proveedor del servicio. Cuando una sesión termina, el entorno se reinicia y se pierden todas las variables y estados almacenados, a menos que se guarden explícitamente en el disco.

In [28]:
ruta_arch = "./asdsad.txt" # ruta y nombre a archivo a LEER desde su drive 
f = open(ruta_arch, 'r') # abre archivo para leer 
print(f.readlines()) # imprime contenido en pantalla 
f.close() # cierra archivo

['jajjajajajaj']


# Repaso de Python

In [29]:
#Ej 1

#Lists
list = [1,2,3,"lat"]
print(list)
for elem in list:
    print(elem)

#Tuple
tuple = ("apple", "bread", "ñoqui")
print(tuple)
print(tuple[0])

#Sets
set1 = {1, 3, 3, 2, 4, 5, 7}
print(set1)

#Dictionary
dict = {"name": "jhonny", "noun": "La gente", "que?": "Esta muy loca"}
for key, value in dict.items():
    print(value)
print(dict.items())

[1, 2, 3, 'lat']
1
2
3
lat
('apple', 'bread', 'ñoqui')
apple
{1, 2, 3, 4, 5, 7}
jhonny
La gente
Esta muy loca
dict_items([('name', 'jhonny'), ('noun', 'La gente'), ('que?', 'Esta muy loca')])


In [30]:
#Ejercicio 2

list1 = [1,2,3,4,5]
list2 = [5,4,3,2,1]

for num1, num2 in zip(list1, list2):
    print(num1, num2)

1 5
2 4
3 3
4 2
5 1


In [1]:
#Ejercicio 3

my_list = [1, 2, 2, 4, 3, 3, 5, 7, 6]

def removeDuplicated(input_list):
    # Transformamos la lista en un set y luego nuevamente en una lista
    print(input_list)
    new_set = set(input_list)
    print(new_set)
    new_list = list(new_set)
    print(new_list)
    return new_list

removeDuplicated(my_list)


[1, 2, 2, 4, 3, 3, 5, 7, 6]
{1, 2, 3, 4, 5, 6, 7}
[1, 2, 3, 4, 5, 6, 7]


[1, 2, 3, 4, 5, 6, 7]

In [2]:
#Ejercicio 4

import math
def distance_between(x1,y1,x2,y2):
    return math.sqrt((x2-x1)**2 + (y2-y1)**2)
    
distance_between(2, 5, 10, 10)

7.0710678118654755

In [5]:
my_list = [10, 20, 30, 40, 50, 60, 70, 80, 90]
sub_list = my_list[1:4] #Sin incluir 4
print(sub_list)

a = ("a", "b", "c", "d", "e", "f", "g", "h")
x = slice(2) #
print(a[x])

a = ("a", "b", "c", "d", "e", "f", "g", "h")
x = slice(3, 5) #sin incluir 5
print(a[x])

[20, 30, 40]
('a', 'b')
('d', 'e')


# Biblioteca NumPy

* numpy.array convierte una lista, tupla u otra estructura de datos similar en un arreglo NumPy. Uso: Útil cuando ya tienes los datos y solo deseas convertirlos en un arreglo de NumPy.

* numpy.empty crea un arreglo sin inicializar sus valores, lo que significa que contendrá los datos que ya estaban en la memoria. Uso: Útil cuando planeas llenar el arreglo inmediatamente después de crearlo, y no te importa el valor inicial. Es más rápido que zeros o ones.

* numpy.full Crea un arreglo y lo llena con un valor específico. Uso: Útil cuando necesitas un arreglo donde todos los elementos tengan el mismo valor.

* numpy.zeros Crea un arreglo lleno de ceros. Uso: Útil cuando necesitas un arreglo de ceros como punto de partida.

* numpy.identity Crea una matriz identidad (una matriz cuadrada con unos en la diagonal principal y ceros en el resto). Uso: Específico para trabajar con álgebra lineal, donde las matrices identidad son comunes.

TIPOS DE DATOS:
* int (enteros)
* float (flotantes)
* complex (números complejos)
* bool (booleanos)
* str (cadenas de texto)
* object (objetos generales)

* Los tipos de datos difieren en el tamaño de los datos que pueden almacenar y en la precisión (por ejemplo, float32 vs float64).
El tipo de dato predeterminado en NumPy es generalmente float64 para arreglos de números, pero esto puede cambiar dependiendo de cómo se crea el arreglo.
El tipo de dato predeterminado para la mayoría de los constructores (zeros, ones, etc.) es float64, pero puedes especificar el tipo usando el parámetro dtype.
No es siempre el mismo; por ejemplo, en numpy.identity, el tipo por defecto es float.


In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4])
print("array", arr)

arr = np.empty((2, 3))
print("empty",arr)

arr = np.full((2, 3), 7) #2 rows, 3 columns, full of number 7
print("full",arr)

arr = np.zeros((2, 3))
print("zeros",arr)

arr = np.identity(3)
print("identity",arr)

array [1 2 3 4]
empty [[7.56605240e-307 7.56587584e-307 1.37961302e-306]
 [1.05699242e-307 1.78022342e-306 8.34449382e-308]]
full [[7 7 7]
 [7 7 7]]
zeros [[0. 0. 0.]
 [0. 0. 0.]]
identity [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
#Funciones relacionadas al tamaño del array

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape) #Devuelve una tupla que indica el tamaño de cada dimensión del array.


arr = np.array([[1, 2, 3], [4, 5, 6]])
print(len(arr)) #Devuelve el tamaño de la primera dimensión del array (es decir, el número de elementos en la primera dimensión).


arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.ndim) #Devuelve el número de dimensiones (o ejes) del array.


arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.size) #Devuelve el número total de elementos en el array.




(2, 3)
2
2
6


**Aplicación sobre Dimensiones Específicas**
Axis (axis): La mayoría de estas funciones de agregación en NumPy aceptan un argumento axis que determina sobre qué dimensión se aplicará la operación.
* axis=0: La operación se aplica a lo largo de las columnas.
* axis=1: La operación se aplica a lo largo de las filas.
* axis=None: (por defecto) La operación se aplica a todos los elementos del array, sin importar la dimensión.

In [20]:
#Ejercicio 3

arr = np.array([[1, 2, 3], [4, 5, 6]])
total_sum = arr.sum() #Suma todos los elementos del array.
sum_by_row = arr.sum(axis=1)  # Suma por filas
sum_by_column = arr.sum(axis=0)  # Suma por columnas
print(total_sum, sum_by_row, sum_by_column)

min_value = arr.min() #Encuentra el valor mínimo en el array. Se puede aplicar sobre una dimension como en el caso anterior
print(min_value)
max_value = arr.max()
print(max_value)

mean_value = arr.mean() #Calcula la media (promedio) de los elementos del array.
print(mean_value)

std_value = arr.std() #Calcula la desviación estándar de los elementos del array.
print(mean_value)

var_value = arr.var() #Calcula la varianza de los elementos del array.
print(std_value)

prod_value = arr.prod()
print(prod_value)

cumsum_value = arr.cumsum()
print(cumsum_value)

cumprod_value = arr.cumprod()
print(cumprod_value)


21 [ 6 15] [5 7 9]
1
6
3.5
3.5
1.707825127659933
720
[ 1  3  6 10 15 21]


**Aplicación de las Funciones**
* Manipulación de Elementos: Las funciones como append, insert, delete, y resize son útiles para modificar el contenido de un array sin cambiar su estructura global.

* Manipulación entre Arreglos: Funciones como concatenate, vstack, hstack, split, y tile permiten combinar o dividir arrays de maneras diferentes, facilitando la creación de estructuras más complejas o la reorganización de datos.

Estas herramientas son fundamentales para manejar datos en proyectos de procesamiento numérico, análisis de datos, y ciencia de datos, donde la flexibilidad y eficiencia en la manipulación de arrays es clave.

In [35]:
# Ejercicio 4

arr = np.array([1, 2, 3])
new_arr = np.append( [4, 5, 6], arr) #Agrega elementos al final de un array. Devuelve un nuevo array extendido.
print("append:", new_arr)

new_arr = np.insert(arr, 1, [9, 8])  # Inserta elementos en un array en la posición especificada. Devuelve un nuevo array.
print("insert:",new_arr)

arr = np.array([1, 2, 3, 4, 5])
new_arr = np.delete(arr, [1, 3])  # Elimina los elementos en las posiciones 1 y 3
print("delete:",new_arr)

arr = np.array([1, 2, 3])
resized_arr = np.resize(arr, (2, 3))  # Cambia el tamaño a 2x3. Rellena con ceros? si es necesario o recortando los elementos sobrantes.
print("resize:",resized_arr)

arr = np.array([1, 2, 3, 4])
flipped_arr = np.flip(arr) #Invierte el orden de los elementos en un array a lo largo de un eje dado.
print("flipped:",flipped_arr)

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
concatenated_arr = np.concatenate((arr1, arr2))
print("concatenated:",concatenated_arr)
#En dos dimensiones:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
concatenated_arr = np.concatenate((arr1, arr2), axis=0)  # Concatenación vertical
print("concatenated vertical:",concatenated_arr)

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
stacked_arr = np.vstack((arr1, arr2)) #Apila arrays en sentido vertical (a lo largo de filas).
print("stacked:",stacked_arr)

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
stacked_arr = np.hstack((arr1, arr2)) #Apila arrays en sentido horizontal (a lo largo de columnas).
print("stacked horizontal:",stacked_arr)

arr = np.array([1, 2, 3, 4, 5, 6])
split_arr = np.split(arr, 3)  # Divide en 3 sub-arrays
print("split:",split_arr)

arr = np.array([1, 2, 3])
tiled_arr = np.tile(arr, 2)  # Repite el array 2 veces
print("tiled:",tiled_arr)

arr = np.array([1, 2, 3])
repeated_arr = np.repeat(arr, 2)  # Repite cada elemento 2 veces
print("repeated:",repeated_arr)


append: [4 5 6 1 2 3]
insert: [1 9 8 2 3]
delete: [1 3 5]
resize: [[1 2 3]
 [1 2 3]]
flipped: [4 3 2 1]
concatenated: [1 2 3 4 5 6]
concatenated vertical: [[1 2]
 [3 4]
 [5 6]
 [7 8]]
stacked: [[1 2 3]
 [4 5 6]]
stacked horizontal: [1 2 3 4 5 6]
split: [array([1, 2]), array([3, 4]), array([5, 6])]
tiled: [1 2 3 1 2 3]
repeated: [1 1 2 2 3 3]


* Slicing en Vectores (1D): Permite seleccionar y modificar partes específicas del vector.
* Slicing en Matrices (2D): Facilita el acceso y modificación de submatrices.
* Slicing en Tensores (3D): Permite trabajar con secciones complejas de un tensor.
* Uso de Step (start:stop:step): Te da control sobre el acceso de elementos con saltos.
Este mecanismo de slicing es muy poderoso y flexible, y se puede utilizar en una variedad de situaciones para manipular arrays de manera eficiente en NumPy.

In [41]:
#Ejercicio 5

import numpy as np

vector = np.array([10, 20, 30, 40, 50, 60])

# Acceder a los elementos de índice 1 a 4 (excluyendo 4)
print("Subvector:", vector[1:4])

# Modificar los elementos del índice 2 a 4 (excluyendo 4)
vector[2:4] = [300, 400]
print("Vector modificado:", vector)

#En matrices (2D):
matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Acceder a las filas 0 a 2 y columnas 1 a 3 (excluyendo 3)
print("Submatriz:\n", matriz[0:2, 1:3])

# Modificar la submatriz seleccionada
matriz[0:2, 1:3] = [[20, 30], [50, 60]]
print("Matriz modificada:\n", matriz)

# Tensor de ejemplo (3x3x3)
tensor = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
                   [[10, 11, 12], [13, 14, 15], [16, 17, 18]],
                   [[19, 20, 21], [22, 23, 24], [25, 26, 27]]])

# Acceder a la slice del tensor que incluye todas las "capas", pero solo las filas 0 a 2 y columnas 1 a 3
print("Subtensor:\n", tensor[:, 0:2, 1:3])

# Acceder a cada segundo elemento del vector
print("Vector con step:", vector[::2])


# Acceder a cada segunda fila y cada segunda columna de la matriz
print("Matriz con step:\n", matriz[::2, ::2])




Subvector: [20 30 40]
Vector modificado: [ 10  20 300 400  50  60]
Submatriz:
 [[2 3]
 [5 6]]
Matriz modificada:
 [[ 1 20 30]
 [ 4 50 60]
 [ 7  8  9]]
Subtensor:
 [[[ 2  3]
  [ 5  6]]

 [[11 12]
  [14 15]]

 [[20 21]
  [23 24]]]
Vector con step: [ 10 300  50]
Matriz con step:
 [[ 1 30]
 [ 7  9]]


In [2]:
import pandas as pd

In [12]:
#Creo diccionario para dsp pasarlo a dataframe
data = {
    'Nombre': ['Juan', 'María', 'Pedro', 'José'],
    'Edad': [20, 26, 18, 22],
    'País': ['Argentina', 'Peru', 'Brasil', 'Chile']
}
dataframe=pd.DataFrame(data)
print(dataframe)

#Imprimo nombre de columnas:
print(dataframe.columns)

#Una forma de agregar a Pablo de 30 años de Colombia es:
#Agrego una nueva fila con loc
dataframe.loc[len(dataframe)] = ["Pablo", 30, "Colombia"]
print(dataframe)
#La funcion append para agregar quedo oobsoleta
#Otra forma de agregar es:
new_row=pd.DataFrame({"Nombre":["Tibu"], "Edad": [20], "País":["Argentina"]})
dataframe= pd.concat([dataframe, new_row], ignore_index=True)
print(dataframe)


#Agregamos al pedro repetido:
dataframe.loc[len(dataframe)] = ["Pedro", 18, "Brasil"]
print(dataframe)
#Eliminamos duplicados:
dataframe = dataframe.drop_duplicates()
print(dataframe)


  Nombre  Edad       País
0   Juan    20  Argentina
1  María    26       Peru
2  Pedro    18     Brasil
3   José    22      Chile
Index(['Nombre', 'Edad', 'País'], dtype='object')
  Nombre  Edad       País
0   Juan    20  Argentina
1  María    26       Peru
2  Pedro    18     Brasil
3   José    22      Chile
4  Pablo    30   Colombia
  Nombre  Edad       País
0   Juan    20  Argentina
1  María    26       Peru
2  Pedro    18     Brasil
3   José    22      Chile
4  Pablo    30   Colombia
5   Tibu    20  Argentina
  Nombre  Edad       País
0   Juan    20  Argentina
1  María    26       Peru
2  Pedro    18     Brasil
3   José    22      Chile
4  Pablo    30   Colombia
5   Tibu    20  Argentina
6  Pedro    18     Brasil
